name: autobuild

on:
  schedule:
    - cron: '0 1 * * *'    # every 1 hour
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - ".github/workflows/**"

permissions:
  contents: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Checkout private source repository
        uses: actions/checkout@v7
        with:
          repository: nuclearmagneton/news
          path: sources/news
          token: ${{ secrets.PRIVATE_SOURCE_TOKEN }}
          fetch-depth: 1
          persist-credentials: false

      - name: Re-generate m3u playlist
        run: |
          cd sources/news/
          bash script.sh
          cd ../../

      - name: Get current India date and time
        id: date
        run: echo "date=$(TZ=Asia/Kolkata date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT

      - name: Commit and push to news repository
        run: |
          cd sources/news/
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "🔁 Update playlists ${{ steps.date.outputs.date }}" || echo "No changes to commit"
          git push https://${{ secrets.PRIVATE_SOURCE_TOKEN }}@github.com/nuclearmagneton/news.git HEAD:master || echo "Nothing to push"
          cd ../../
